import type { Scholarship } from "./matching";

/** Sample catalog. In production this lives in Supabase (see supabase/schema.sql). */
export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "stem-women",
    name: "Women in STEM Excellence Award",
    amount: 10000,
    minGpa: 3.5,
    majors: ["computer science", "engineering", "mathematics", "physics"],
    years: [],
    states: [],
    citizenship: ["us", "permanent_resident"],
    needBased: false,
    firstGenOnly: false,
    targetActivities: ["robotics", "coding", "research"],
    tags: ["STEM", "merit"],
  },
  {
    id: "first-gen-grant",
    name: "First Generation Trailblazer Grant",
    amount: 5000,
    minGpa: 3.0,
    majors: [],
    years: ["freshman", "sophomore"],
    states: [],
    citizenship: [],
    needBased: true,
    firstGenOnly: true,
    targetActivities: ["volunteering", "leadership"],
    tags: ["need-based", "first-gen"],
  },
  {
    id: "ca-future-leaders",
    name: "California Future Leaders Scholarship",
    amount: 7500,
    minGpa: 3.2,
    majors: [],
    years: [],
    states: ["california", "ca"],
    citizenship: ["us"],
    needBased: true,
    firstGenOnly: false,
    targetActivities: ["debate", "student government", "leadership"],
    tags: ["regional", "leadership"],
  },
  {
    id: "cs-innovators",
    name: "Computer Science Innovators Fund",
    amount: 15000,
    minGpa: 3.4,
    majors: ["computer science"],
    years: ["junior", "senior", "graduate"],
    states: [],
    citizenship: [],
    needBased: false,
    firstGenOnly: false,
    targetActivities: ["coding", "open source", "hackathons"],
    tags: ["STEM", "merit"],
  },
  {
    id: "community-service",
    name: "Community Impact Service Award",
    amount: 3000,
    minGpa: 2.8,
    majors: [],
    years: [],
    states: [],
    citizenship: [],
    needBased: true,
    firstGenOnly: false,
    targetActivities: ["volunteering", "community service"],
    tags: ["service"],
  },
  {
    id: "global-scholars",
    name: "Global Scholars International Award",
    amount: 12000,
    minGpa: 3.6,
    majors: [],
    years: [],
    states: [],
    citizenship: ["international"],
    needBased: true,
    firstGenOnly: false,
    targetActivities: ["research", "languages"],
    tags: ["international", "need-based"],
  },
];
